import { Injectable } from '@angular/core';
import { Funcionalidad } from '../../models/funcionalidad';
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';
import { environment } from 'src/environments/environment';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class FuncionalidadService {

  url: string = `${environment.HOST_URL}/funcionalidades`;
  constructor(private http: HttpClient) { }
  listar() {
    return this.http.get<Funcionalidad[]>(this.url);
  }

  registrar(data: Funcionalidad) {
    return this.http.post(this.url, data);
  }

  modificar(data: Funcionalidad) {
    return this.http.put(this.url, data);
  }

  eliminar(id: number) {
    return this.http.delete(`${this.url}/${id}`);
  }

  getFuncionalidades(term: string = null): Observable<Funcionalidad[]> {
    let items = getlistaFuncionalidades();
    if (term) {
        items = items.filter(x => (x.funnom.toLocaleLowerCase().indexOf(term.toLocaleLowerCase()) > -1));
    }
    return of(items).pipe(delay(500));
  }
}

function getlistaFuncionalidades() {
  return [
    {
        "funcod": 1504,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-09-17",
        "funsig": "SIAM_FN_BUSASIG                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-09-17",
        "funnom": "BUSCA EQUIPOS ASIGNADOS"
    },
    {
        "funcod": 1553,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-28",
        "funsig": "SISPAN_FN_LISTTIPPAN                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "LISTADO DEL TIPO DE PANEL",
        "fecreg": "2015-10-28",
        "funnom": "LISTADO DEL TIPO DE PANEL"
    },
    {
        "funcod": 1554,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-28",
        "funsig": "SISPAN_FN_LISTTIPTER                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "LISTADO DEL TIPO DE TERMINO",
        "fecreg": "2015-10-28",
        "funnom": "LISTADO DEL TIPO DE TERMINO"
    },
    {
        "funcod": 1556,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-28",
        "funsig": "SISPAN_FN_CONSPAN                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTA PANELES PUBLICITARIOS",
        "fecreg": "2015-10-28",
        "funnom": "CONSULTA PANELES PUBLICITARIOS"
    },
    {
        "funcod": 1557,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-28",
        "funsig": "SISPAN_FN_CONSNOTIF                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTA NOTIFCACIONES",
        "fecreg": "2015-10-28",
        "funnom": "CONSULTA NOTIFCACIONES"
    },
    {
        "funcod": 2482,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-07-20",
        "funsig": "MOD_FICHA                                         ",
        "funest": "1",
        "usureg": null,
        "fundes": "EDITAR FICHA",
        "fecreg": "2016-07-20",
        "funnom": "EDITAR FICHA"
    },
    {
        "funcod": 2652,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_SEG_REGISTRADO                       ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR SEGUIMIENTO DE RECOMENDACIONES EN ESTADO 'REGISTRADO'",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR SEGTO. DE RECOMEN. - 'REGISTRADO'"
    },
    {
        "funcod": 2653,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_SEG_PENDIENTE                        ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR SEGUIMIENTO DE RECOMENDACIONES EN ESTADO 'PENDIENTE'",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR SEGTO. DE RECOMEN - 'PENDIENTE'"
    },
    {
        "funcod": 2654,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_SEG_PROCESO                          ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR SEGUIMIENTO DE RECOMENDACIONES EN ESTADO 'EN PROCESO'",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR SEGTO. DE RECOMEN - 'EN PROCESO'"
    },
    {
        "funcod": 2655,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_SEG_IMPLEMENTACION_AREA              ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR SEGUIMIENTO DE RECOMENDACIONES EN ESTADO 'IMPLEMENT. AREA'",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR SEGTO. DE RECOMEN - 'IMPLEMENT. AREA'"
    },
    {
        "funcod": 2656,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_SEG_IMPLEMENTACION_MONITOR           ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR SEGUIMIENTO DE RECOMENDACIONES EN ESTADO 'IMPLEMENT. MONITOR'",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR SEGTO. DE RECOMEN - 'IMPLEMENT. MONITOR'"
    },
    {
        "funcod": 2657,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_SEG_VENCIDO                          ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR SEGUIMIENTO DE RECOMENDACIONES EN ESTADO 'VENCIDO'",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR SEGTO. DE RECOMEN - 'VENCIDO'"
    },
    {
        "funcod": 2658,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_REG_ACCION                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR ACCIÓN",
        "fecreg": "2016-09-21",
        "funnom": "REGISTRAR ACCIÓN"
    },
    {
        "funcod": 2659,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_ACCION                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR ACCIÓN",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR ACCIÓN"
    },
    {
        "funcod": 2660,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_MOD_ACCION                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "MODIFICAR ACCIÓN",
        "fecreg": "2016-09-21",
        "funnom": "MODIFICAR ACCIÓN"
    },
    {
        "funcod": 2661,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_FICHA_SEGUIMIENTO                    ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR FICHA DE SEGUIMIENTO",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR FICHA DE SEGUIMIENTO"
    },
    {
        "funcod": 2662,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_GEN_FICHA_SEGUIMIENTO                    ",
        "funest": "1",
        "usureg": null,
        "fundes": "GENERAR FICHA DE SEGUIMIENTO",
        "fecreg": "2016-09-21",
        "funnom": "GENERAR FICHA DE SEGUIMIENTO"
    },
    {
        "funcod": 2663,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_REG_RESPUESTA_FICHA                      ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR RESPUESTA POR RECOMENDACIÓN",
        "fecreg": "2016-09-21",
        "funnom": "REGISTRAR RESPUESTA POR RECOMENDACIÓN"
    },
    {
        "funcod": 2664,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_GEN_RSPT_FICHA_SEGUIMIENTO               ",
        "funest": "1",
        "usureg": null,
        "fundes": "GENERAR RESPUESTA DE FICHA DE SEGUIMIENTO",
        "fecreg": "2016-09-21",
        "funnom": "GENERAR RESPUESTA DE FICHA DE SEGUIMIENTO"
    },
    {
        "funcod": 2665,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_ALERTAS                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR ALERTAS",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR ALERTAS"
    },
    {
        "funcod": 2764,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-10-31",
        "funsig": "REIMPRESION                                       ",
        "funest": "1",
        "usureg": null,
        "fundes": "IMPRIMISION DE  TICKET ",
        "fecreg": "2016-10-31",
        "funnom": "REIMPRESION"
    },
    {
        "funcod": 4188,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-02-07",
        "funsig": "INHAB_SOBRANTE                                    ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-02-07",
        "funnom": "INHABILITAR SOBRANTE"
    },
    {
        "funcod": 4270,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-02-28",
        "funsig": "SW_RTINP_ACPERNAT15                               ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-02-28",
        "funnom": "MANTENIMIENTO PERSONA"
    },
    {
        "funcod": 45,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_VIA                                      ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR LA VIA",
        "fecreg": "2013-05-09",
        "funnom": "CAMBIAR VIA"
    },
    {
        "funcod": 113,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMFECCASO                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR LA FECHA DE INICIO DEL CASO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR FECHA CASO"
    },
    {
        "funcod": 114,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMTERCIV                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR EL TERCERO CIVILMENTE RESPONSABLE",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR TERCERO CASO"
    },
    {
        "funcod": 115,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_CAMOBSCAS                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR OBSERVACIÓN DEL CASO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR OBSERVACION CASO"
    },
    {
        "funcod": 116,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMESTCASO                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR ESTADO DEL CASO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR ESTADO CASO"
    },
    {
        "funcod": 123,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-11",
        "funsig": "JUDIC_FN_AGRRESO                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR RESOLUCION",
        "fecreg": "2013-06-11",
        "funnom": "AGREGAR RESOLUCION"
    },
    {
        "funcod": 124,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-11",
        "funsig": "JUDIC_FN_CAMRES                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR RESOLUCION",
        "fecreg": "2013-06-11",
        "funnom": "CAMBIAR RESOLUCION"
    },
    {
        "funcod": 125,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-11",
        "funsig": "JUDIC_FN_ELIRES                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR RESOLUCION",
        "fecreg": "2013-06-11",
        "funnom": "ELIMINAR RESOLUCION"
    },
    {
        "funcod": 56,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_AGR_PAS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR NUEVO PASO",
        "fecreg": "2013-05-09",
        "funnom": "AGREGAR PASO"
    },
    {
        "funcod": 104,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMCUASOL                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR LA CUANTIA SOLICITADA",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR CUANTIA SOLICITADA"
    },
    {
        "funcod": 105,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-06",
        "funsig": "JUDIC_FN_CAMCUASEN                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIA CUANTIA SENTENCIADA",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR CUANTIA SENTENCIADA"
    },
    {
        "funcod": 106,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMUBIFIS                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR LA UBICACIÓN FÍSICA DEL EXPEDIENTE DEL CASO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR UBICACIÓN FISICA"
    },
    {
        "funcod": 107,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMGIRO                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR GIRO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR GIRO"
    },
    {
        "funcod": 108,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMASUN                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR ASUNTO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR ASUNTO"
    },
    {
        "funcod": 109,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMTIEMEST                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR TIEMPO ESTIMADO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR TIEMPO ESTIMADO"
    },
    {
        "funcod": 119,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-06",
        "funsig": "JUDIC_FN_AGRDELCASO                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR DELITO AL CASO",
        "fecreg": "2013-06-06",
        "funnom": "AGREGAR DELITO CASO"
    },
    {
        "funcod": 129,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-12",
        "funsig": "JUDIC_FN_AGR_PAGO                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR PAGO",
        "fecreg": "2013-06-12",
        "funnom": "AGREGAR PAGO"
    },
    {
        "funcod": 130,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-12",
        "funsig": "JUDIC_FN_CAM_PAGO                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR PAGO",
        "fecreg": "2013-06-12",
        "funnom": "CAMBIAR PAGO"
    },
    {
        "funcod": 131,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-12",
        "funsig": "JUDIC_FN_ELI_PAGO                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR PAGO",
        "fecreg": "2013-06-12",
        "funnom": "ELIMINAR PAGO"
    },
    {
        "funcod": 46,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_PROCESO                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR EL PROCESO",
        "fecreg": "2013-05-09",
        "funnom": "CAMBIAR PROCESO"
    },
    {
        "funcod": 47,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_ELI_LIT                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR LITIGANTES",
        "fecreg": "2013-05-09",
        "funnom": "ELIMINAR LITIGANTE"
    },
    {
        "funcod": 57,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_ELI_PAS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR UN PASO",
        "fecreg": "2013-05-09",
        "funnom": "ELIMINAR PASO"
    },
    {
        "funcod": 72,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_CAMTDT                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR TIPO DE DOCUMENTO",
        "fecreg": "2013-05-14",
        "funnom": "CAMBIAR TIPO DE DOCUMENTO"
    },
    {
        "funcod": 73,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_CAMREC                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR RECEPTOR",
        "fecreg": "2013-05-14",
        "funnom": "CAMBIAR RECEPTOR"
    },
    {
        "funcod": 74,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_ACTPAS                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ACTUALIZAR PASO",
        "fecreg": "2013-05-14",
        "funnom": "ACTUALIZAR PASO"
    },
    {
        "funcod": 75,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_ACTNOT                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ACTUALIZAR NOTIFICACION",
        "fecreg": "2013-05-14",
        "funnom": "ACTUALIZAR NOTIFICACION"
    },
    {
        "funcod": 76,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_AGRPRE                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR PRETENCION",
        "fecreg": "2013-05-14",
        "funnom": "AGREGAR PRETENCION"
    },
    {
        "funcod": 77,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_ELIPRE                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR PRETENCIONES",
        "fecreg": "2013-05-14",
        "funnom": "ELIMINAR PRETENCION"
    },
    {
        "funcod": 78,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_EDIDES                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE EDITAR DELITOS ESPECIFICOS",
        "fecreg": "2013-05-14",
        "funnom": "EDITAR DELITO ESPECIFICO"
    },
    {
        "funcod": 79,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_ELIDES                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR DELITO ESPECIFICO",
        "fecreg": "2013-05-14",
        "funnom": "ELIMINAR DELITO ESPECIFICO"
    },
    {
        "funcod": 80,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-14",
        "funsig": "JUDIC_FN_ELINOT                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR NOTIFICACION",
        "fecreg": "2013-05-14",
        "funnom": "ELIMINAR NOTIFICACION"
    },
    {
        "funcod": 118,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-06",
        "funsig": "JUDIC_CAM_PRETCASO                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR LA PRETENSION DEL CASO",
        "fecreg": "2013-06-06",
        "funnom": "CAMBIAR PRETENSION CASO"
    },
    {
        "funcod": 120,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-06",
        "funsig": "JUDIC_FN_CAMCASO                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR INFORMACIÓN DEL CASO",
        "fecreg": "2013-06-06",
        "funnom": "CAMBIAR CASO"
    },
    {
        "funcod": 6,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-01-28",
        "funsig": "SISPLA_ADD_INDEST                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE REGISTRAR LOS INDICADORES ESTRATEGICOS",
        "fecreg": "2013-01-28",
        "funnom": "AGREGAR INDICADOR ESTRATEGICO"
    },
    {
        "funcod": 16,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SISLIC_ADD_USUARIO                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE REGISTRAR NUEVOS USUARIOS",
        "fecreg": "2013-01-30",
        "funnom": "AGERGAR USUARIO"
    },
    {
        "funcod": 17,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-03-04",
        "funsig": "SISLIC_ADD_LICENCIA                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE REGISTRAR LAS LICENCIAS",
        "fecreg": "2013-01-30",
        "funnom": "AGREGAR LICENCIA"
    },
    {
        "funcod": 26,
        "estreg": "0",
        "usumod": null,
        "fecmod": "2013-03-04",
        "funsig": "SIGERE_ADD_USUARIO                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE REGISTRAR NUEVOS USUARIOS",
        "fecreg": "2013-02-01",
        "funnom": "AGREGAR USUARIO"
    },
    {
        "funcod": 27,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIGERE_ADD_RESOL                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE REGISTRAR NUEVA RESOLUCION",
        "fecreg": "2013-02-01",
        "funnom": "AGREGAR RESOLUCION"
    },
    {
        "funcod": 28,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-01-28",
        "funsig": "SISACI_LOGIN_SYSTEM                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE INGRESAR AL SISTEMA",
        "fecreg": "2013-01-28",
        "funnom": "INGRESAR SISTEMA SISACI"
    },
    {
        "funcod": 1,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-01-28",
        "funsig": "SISPLA_ADD_EJEPRO                                 ",
        "funest": "0",
        "usureg": null,
        "fundes": "PERMITE REGISTRAR NUEVOS EJES PROGRAMATICOS",
        "fecreg": "2013-01-28",
        "funnom": "AGREGAR EJE PROGRAMATICO"
    },
    {
        "funcod": 3,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SISPLA_ADD_OEG                                    ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE EL REGISTRO DE OBJETIVOS ESTRATEGICOS GENERALES",
        "fecreg": "2013-01-28",
        "funnom": "AGREGAR OBJETIVO ESTRATEGICO GENERAL"
    },
    {
        "funcod": 43,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_MAT                                      ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AL USUARIO MODIFICAR LA MATERIA DEL CASO",
        "fecreg": "2013-05-09",
        "funnom": "CAMBIAR MATERIA"
    },
    {
        "funcod": 48,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_AGR_DE                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR DEMANDANTE",
        "fecreg": "2013-05-09",
        "funnom": "AGREGAR DEMANDANTE"
    },
    {
        "funcod": 49,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_AGR_DO                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR DEMANDADO",
        "fecreg": "2013-05-09",
        "funnom": "AGREGAR DEMANDADO"
    },
    {
        "funcod": 50,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_ELI_DO                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR DEMANDADO",
        "fecreg": "2013-05-09",
        "funnom": "ELIMINAR DEMANDADO"
    },
    {
        "funcod": 52,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_ELI_DE                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR DEMANDANTE",
        "fecreg": "2013-05-09",
        "funnom": "ELIMINAR DEMANDANTE"
    },
    {
        "funcod": 53,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_AGR_LIT                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR UN LITIGANTE",
        "fecreg": "2013-05-09",
        "funnom": "AGREGAR LITIGANTE"
    },
    {
        "funcod": 54,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_REA_ABO                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE REASIGNAR ABOGADO",
        "fecreg": "2013-05-09",
        "funnom": "REASIGNAR ABOGADO"
    },
    {
        "funcod": 55,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_AGR_NUE_CAS                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR NUEVO CASO",
        "fecreg": "2013-05-09",
        "funnom": "AGREGAR NUEVO CASO"
    },
    {
        "funcod": 58,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-09",
        "funsig": "JUDIC_FN_AGR_NOT                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR UNA NOTIFICACION",
        "fecreg": "2013-05-09",
        "funnom": "AGREGAR NOTIFICACION"
    },
    {
        "funcod": 110,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMACTADM                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR ACTO ADMINISTRATIVO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR ACTO ADMINISTRATIVO"
    },
    {
        "funcod": 112,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-06-05",
        "funsig": "JUDIC_FN_CAMDESCASO                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CAMBIAR DESCRIPCIÓN DEL CASO",
        "fecreg": "2013-06-05",
        "funnom": "CAMBIAR DESCRIPCIÓN CASO"
    },
    {
        "funcod": 588,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_UNIMED_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR UNIDADES DE MEDIDA",
        "fecreg": "2014-01-21",
        "funnom": "LISTAR UNIDAD DE MEDIDA"
    },
    {
        "funcod": 589,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_CLACUE_CRE                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR CLASIFICADOR CUENTA",
        "fecreg": "2014-01-21",
        "funnom": "CREAR CLASIFICADOR CUENTA"
    },
    {
        "funcod": 590,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_CLACUE_MOD                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR CLASIFICADOR CUENTA",
        "fecreg": "2014-01-21",
        "funnom": "MODIFICAR CLASIFICADOR CUENTA"
    },
    {
        "funcod": 591,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_CLACUE_CON                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR CLASIFICADOR CUENTA",
        "fecreg": "2014-01-21",
        "funnom": "CONSULTAR CLASIFICADOR CUENTA"
    },
    {
        "funcod": 592,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_CLACUE_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR CLASIFICADOR CUENTA",
        "fecreg": "2014-01-21",
        "funnom": "LISTAR CLASIFICADOR CUENTA"
    },
    {
        "funcod": 632,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-02-10",
        "funsig": "SAFIM_FN_CLACUE_CUE                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR LA CUENTAS DE CLASIFICADOR CUENTA",
        "fecreg": "2014-02-10",
        "funnom": "MODIFICAR CUENTA DE CLASIFICADOR CUENTA"
    },
    {
        "funcod": 694,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-19",
        "funsig": "SAFIM_FN_USUCEN_OBT                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE OBTENER LOS CENTROS DE COSTO ASIGNADOS A UN USUARIO",
        "fecreg": "2014-03-19",
        "funnom": "OBTENER CENTROS DE COSTO"
    },
    {
        "funcod": 695,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-19",
        "funsig": "SAFIM_FN_PEDBS_CON                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR PEDIDO DE BB SS",
        "fecreg": "2014-03-19",
        "funnom": "CONSULTAR PEDIDO BB SS"
    },
    {
        "funcod": 696,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-19",
        "funsig": "SAFIM_FN_PEDBS_OBR                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE OBTENER EL RESUMEN DE PEDIDOS BB SS",
        "fecreg": "2014-03-19",
        "funnom": "OBTENER RESUMEN DE PEDIDOS BB SS"
    },
    {
        "funcod": 697,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-19",
        "funsig": "SAFIM_FN_DEP_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR DEPENDENCIAS",
        "fecreg": "2014-03-19",
        "funnom": "LISTAR DEPENDENCIA"
    },
    {
        "funcod": 700,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-19",
        "funsig": "SAFIM_FN_PEDBSI_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR LOS ITEMS DE PEDIDO BB SS",
        "fecreg": "2014-03-19",
        "funnom": "LISTAR ITEMS DE PEDIDO BB SS"
    },
    {
        "funcod": 702,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-19",
        "funsig": "SAFIM_FN_PEDBS_ACH                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ACTUALIZAR EL ARCHIVO DEL PEDIDO DE BB SS",
        "fecreg": "2014-03-19",
        "funnom": "ACTUALIZAR ARCHIVO DE PEDIDO BB SS"
    },
    {
        "funcod": 753,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-04-14",
        "funsig": "SAFIM_FN_PRE_CONACT                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR PRESUPUESTO ACTUAL",
        "fecreg": "2014-04-14",
        "funnom": "OBTENER PRESUPUESTO ACTUAL"
    },
    {
        "funcod": 295,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-08-12",
        "funsig": "JDC_FUN_MODRESSAN                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR EL MONTO DE LA RESOLUCIÓN DE SANCION",
        "fecreg": "2013-08-12",
        "funnom": "MODIFICAR RESOLUCIÓN DE SANCION"
    },
    {
        "funcod": 561,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_GRU_CRE                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR GRUPO",
        "fecreg": "2014-01-20",
        "funnom": "CREAR GRUPO"
    },
    {
        "funcod": 562,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_GRU_MOD                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR GRUPO",
        "fecreg": "2014-01-20",
        "funnom": "MODIFICAR GRUPO"
    },
    {
        "funcod": 563,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_GRU_CON                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE OBTENER DATOS DE UN GRUPO",
        "fecreg": "2014-01-20",
        "funnom": "CONSULTAR GRUPO"
    },
    {
        "funcod": 564,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_GRU_ELI                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR GRUPO",
        "fecreg": "2014-01-20",
        "funnom": "ELIMINAR GRUPO"
    },
    {
        "funcod": 565,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_GRU_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR GRUPOS",
        "fecreg": "2014-01-20",
        "funnom": "LISTAR GRUPO"
    },
    {
        "funcod": 567,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_CLA_CRE                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR CLASE",
        "fecreg": "2014-01-20",
        "funnom": "CREAR CLASE"
    },
    {
        "funcod": 568,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_CLA_MOD                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR CLASE",
        "fecreg": "2014-01-20",
        "funnom": "MODIFICAR CLASE"
    },
    {
        "funcod": 569,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_CLACUE_ELI                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR CLASIFICADOR CUENTA",
        "fecreg": "2014-01-20",
        "funnom": "ELIMINAR CLASIFICADOR CUENTA"
    },
    {
        "funcod": 570,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_CLA_CON                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE OBTENER DATOS DE CLASE",
        "fecreg": "2014-01-20",
        "funnom": "CONSULTAR CLASE"
    },
    {
        "funcod": 571,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_CLA_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR CLASE",
        "fecreg": "2014-01-20",
        "funnom": "LISTAR CLASE"
    },
    {
        "funcod": 572,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_CLA_ELI                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR CLASE",
        "fecreg": "2014-01-20",
        "funnom": "ELIMINAR CLASE"
    },
    {
        "funcod": 573,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_FAM_CRE                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR FAMILIA",
        "fecreg": "2014-01-20",
        "funnom": "CREAR FAMILIA"
    },
    {
        "funcod": 574,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_FAM_MOD                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR FAMILIA",
        "fecreg": "2014-01-20",
        "funnom": "MODIFICAR FAMILIA"
    },
    {
        "funcod": 575,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_FAM_ELI                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR FAMILIA",
        "fecreg": "2014-01-20",
        "funnom": "ELIMINAR FAMILIA"
    },
    {
        "funcod": 576,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_FAM_CON                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE OBTENER DATOS DE FAMILIA",
        "fecreg": "2014-01-20",
        "funnom": "CONSULTAR FAMILIA"
    },
    {
        "funcod": 577,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_FAM_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR FAMILIAS",
        "fecreg": "2014-01-20",
        "funnom": "LISTAR FAMILIA"
    },
    {
        "funcod": 578,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_ITE_CRE                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR ITEM",
        "fecreg": "2014-01-20",
        "funnom": "CREAR ITEM"
    },
    {
        "funcod": 579,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_ITE_MOD                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR ITEM",
        "fecreg": "2014-01-20",
        "funnom": "MODIFICAR ITEM"
    },
    {
        "funcod": 580,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_ITE_ELI                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR ITEM",
        "fecreg": "2014-01-20",
        "funnom": "ELIMINAR ITEM"
    },
    {
        "funcod": 581,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_ITE_CON                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR ITEM",
        "fecreg": "2014-01-20",
        "funnom": "CONSULTAR ITEM"
    },
    {
        "funcod": 582,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "funsig": "SAFIM_FN_ITE_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR ITEMS",
        "fecreg": "2014-01-20",
        "funnom": "LISTAR ITEM"
    },
    {
        "funcod": 708,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-25",
        "funsig": "SAFIM_FN_PEDBSI_CRE                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR ITEM PEDIDO DE BB SS",
        "fecreg": "2014-03-25",
        "funnom": "CREAR ITEM PEDIDO BB SS"
    },
    {
        "funcod": 709,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-25",
        "funsig": "SAFIM_FN_PEDBSI_MOD                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR ITEM DE PEDIDO DE BB SS",
        "fecreg": "2014-03-25",
        "funnom": "MODIFICAR ITEM PEDIDO BB SS"
    },
    {
        "funcod": 710,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-25",
        "funsig": "SAFIM_FN_PEDBSI_ELI                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR ITEM DE PEDIDO DE BB SS",
        "fecreg": "2014-03-25",
        "funnom": "ELIMINAR ITEM PEDIDO BB SS"
    },
    {
        "funcod": 718,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-27",
        "funsig": "SAFIM_FN_TIPREC_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR EL TIPO DE RECURSO",
        "fecreg": "2014-03-27",
        "funnom": "LISTAR TIPO DE RECURSO"
    },
    {
        "funcod": 754,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-04-14",
        "funsig": "SAFIM_FN_PRE_CONTRA                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR PRESUPUESTO EN TRAMITE",
        "fecreg": "2014-04-14",
        "funnom": "OBTENER PRESUPUESTO EN TRAMITE"
    },
    {
        "funcod": 755,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-04-14",
        "funsig": "SAFIM_FN_PLACUE_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR PLAN DE CUENTAS",
        "fecreg": "2014-04-14",
        "funnom": "LISTAR PLAN CUENTA"
    },
    {
        "funcod": 1551,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-28",
        "funsig": "SISPAN_FN_REPLIQ                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "IMPRIMIR REPORTE DE LIQUIDACIÓN DE ELEMENTOS PUBLICITARIOS",
        "fecreg": "2015-10-28",
        "funnom": "LIQUIDACION - ELEMENTOS PUBLICITARIOS"
    },
    {
        "funcod": 1598,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQTRH_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR RECIBOS POR HONORARIOS",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR RECIBOS POR HONORARIOS"
    },
    {
        "funcod": 1599,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_FECCIE_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR FECHA DE CIERRE",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR FECHA CIERRE"
    },
    {
        "funcod": 1600,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQTRH_ELI                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR RECIBOS POR HONORARIOS",
        "fecreg": "2015-11-27",
        "funnom": "ELIMINAR RECIBO POR HONORARIOS"
    },
    {
        "funcod": 1601,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQTER_MOD                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR EL REQUERIMIENTO SNP IMP",
        "fecreg": "2015-11-27",
        "funnom": "MODIFICAR REQUERIMIENTO SNP IMP"
    },
    {
        "funcod": 1602,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_FECCIE_ACTR                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ACTIVAR REQUERIMIENTO DE GASTO",
        "fecreg": "2015-11-27",
        "funnom": "ACTIVAR REQUERIMIENTO DE GASTO"
    },
    {
        "funcod": 1603,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQCAB_CON                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE OBTENER DATOS DE UN REQUERIMIENTO DE GASTO",
        "fecreg": "2015-11-27",
        "funnom": "CONSULTAR REQUERIMIENTO DE GASTO"
    },
    {
        "funcod": 1604,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQTRH_CON                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR RECIBOS POR HONORARIO",
        "fecreg": "2015-11-27",
        "funnom": "CONSULTAR RECIBO POR HONORARIOS"
    },
    {
        "funcod": 1605,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQTRH_CRE                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR RECIBOS POR HONORARIOS",
        "fecreg": "2015-11-27",
        "funnom": "CREAR RECIBO POR HONORARIOS"
    },
    {
        "funcod": 1606,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_TBLUSE_CON                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR DATOS DE UN USUARIO",
        "fecreg": "2015-11-27",
        "funnom": "CONSULTAR USUARIO"
    },
    {
        "funcod": 1607,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_TREQGA_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR EL TIPO DE REQUERIMIENTO DE GASTO",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR TIPO REQUERIMIENTO DE GASTO"
    },
    {
        "funcod": 1608,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_DCALEN_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR EL TIPO DE GASTO",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR TIPO DE GASTO"
    },
    {
        "funcod": 1609,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_TCALEN_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR EL CONCEPTO DE GASTO",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR CONCEPTO DE GASTO"
    },
    {
        "funcod": 1610,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REGNUM_BLOR                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR SI EN NUMERO DE REGISTRO SE ENCUENTRA BLOQUEADO",
        "fecreg": "2015-11-27",
        "funnom": "CONSULTA NUMERO REGISTRO BLOQUEADO"
    },
    {
        "funcod": 1611,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQCAB_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR REQUERIMIENTO D EGASTO",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR REQUERIMIENTO DE GASTO"
    },
    {
        "funcod": 1612,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_DOCAPR_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR DOCUMENTOS PARA COMPRAS/ ADQUISICIONES",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR DOCUMENTOS PARA ADQUISICIONES"
    },
    {
        "funcod": 1613,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQDET_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR LOS ITEMS DE LOS REQUERIMIENTOS DE GASTO",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR ITEMS DE REQUERIMIENTO DE GASTO"
    },
    {
        "funcod": 1614,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_REQTRH_MOD                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR RECIBOS POR HONORARIOS",
        "fecreg": "2015-11-27",
        "funnom": "MODIFICAR RECIBO POR HONORARIOS"
    },
    {
        "funcod": 1615,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_PROVEE_LIS                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR PROVEEDORES",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR PROVVEDOR"
    },
    {
        "funcod": 1616,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_ACTO                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": "ACCESO TOTAL POR DESARROLLO",
        "fecreg": "2015-11-27",
        "funnom": "PARA DESARROLLO"
    },
    {
        "funcod": 1617,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_CENCOS                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "FUNCIONALIDAD CENTRO COSTOS",
        "fecreg": "2015-11-27",
        "funnom": "FUNCIONALIDAD CENTRO COSTOS"
    },
    {
        "funcod": 1618,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-27",
        "funsig": "SAFIM_FN_PROPRE                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "LISTAR PROGRAMACION PRESUPUESTARIA",
        "fecreg": "2015-11-27",
        "funnom": "LISTAR PROGRAMACION PRESUPUESTARIA"
    },
    {
        "funcod": 2019,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "LCVM_ADD_CONDUCTOR                                ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "REGISTRAR CONDUCTOR"
    },
    {
        "funcod": 2022,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "SW_RTINP_CS01                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "RTI CREAR SOLICITUD"
    },
    {
        "funcod": 2023,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "SW_RTINP_EE02                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "RTI EXPORTAR EXCEL"
    },
    {
        "funcod": 2024,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "SW_RTINP_VR03                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "RTI VER REPORTE"
    },
    {
        "funcod": 2025,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "SW_RTINP_VDPE04                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "RTI VER DETALLE POR EXPEDIENTE"
    },
    {
        "funcod": 2026,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "SW_RTINP_DEPR05                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "RTI DETALLE EDITAR PROPIETARIO"
    },
    {
        "funcod": 2027,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "SW_RTINP_DEVE06                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "RTI DETALLE EDITAR VEHICULO"
    },
    {
        "funcod": 2028,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "SW_RTINP_NITUCR07                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "RTI NO IMPRIME TUC - RESOLUCION"
    },
    {
        "funcod": 2029,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-06",
        "funsig": "SW_RTINP_AEPSUP08                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-06",
        "funnom": "RTI APRUEBA EDICION PROPIET- SUPERV"
    },
    {
        "funcod": 2160,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-25",
        "funsig": "SAFIM_FUN_CREARPROVI                              ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-25",
        "funnom": "CREAR PROVISION GASTO"
    },
    {
        "funcod": 2337,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-05-25",
        "funsig": "LCVM_REGULARIZA_LIC                               ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-05-25",
        "funnom": "REGULARIZAR LICENCIA VM"
    },
    {
        "funcod": 2634,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_MNT_PARAMETRO                            ",
        "funest": "1",
        "usureg": null,
        "fundes": "MANTENIMIENTO DE PARÁMETROS",
        "fecreg": "2016-09-21",
        "funnom": "MANTENIMIENTO DE PARÁMETROS"
    },
    {
        "funcod": 2635,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_MNT_ALERTAS                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "MANTENIMIENTO DE ALERTAS",
        "fecreg": "2016-09-21",
        "funnom": "MANTENIMIENTO DE ALERTAS"
    },
    {
        "funcod": 2636,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_MNT_UNIDAD_ORGANIZATIVA                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "MANTENIMIENTO DE UNIDADES ORGANIZATIVAS",
        "fecreg": "2016-09-21",
        "funnom": "MANTENIMIENTO DE UNIDADES ORGANIZATIVAS"
    },
    {
        "funcod": 2637,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_MNT_ROL_USUARIO                          ",
        "funest": "1",
        "usureg": null,
        "fundes": "ASIGNACIÓN DE USUARIOS A ROLES",
        "fecreg": "2016-09-21",
        "funnom": "ASIGNACIÓN DE USUARIOS A ROLES"
    },
    {
        "funcod": 2638,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_REG_INFORME                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRO DE INFORMES",
        "fecreg": "2016-09-21",
        "funnom": "REGISTRO DE INFORMES"
    },
    {
        "funcod": 584,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_UNIMED_CRE                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR UNIDAD DE MEDIDA",
        "fecreg": "2014-01-21",
        "funnom": "CREAR UNIDAD DE MEDIDA"
    },
    {
        "funcod": 585,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_UNIMED_MOD                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR UNIDAD DE MEDIDA",
        "fecreg": "2014-01-21",
        "funnom": "MODIFICAR UNIDAD DE MEDIDA"
    },
    {
        "funcod": 586,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_UNIMED_ELI                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR UNIDAD DE MEDIDA",
        "fecreg": "2014-01-21",
        "funnom": "ELIMINAR UNIDAD DE MEDIDA"
    },
    {
        "funcod": 587,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-21",
        "funsig": "SAFIM_FN_UNIMED_CON                               ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR DATOS DE UNIDAD DE MEDIDA",
        "fecreg": "2014-01-21",
        "funnom": "CONSULTAR UNIDAD DE MEDIDA"
    },
    {
        "funcod": 706,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-25",
        "funsig": "SAFIM_FN_PEDBS_MOD                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE MODIFICAR PEDIDO BB SS",
        "fecreg": "2014-03-20",
        "funnom": "MODIFICAR PEDIDO BB SS"
    },
    {
        "funcod": 713,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-26",
        "funsig": "SAFIM_FN_ACT_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR ACTIVIDAD",
        "fecreg": "2014-03-26",
        "funnom": "LISTAR ACTIVIDAD"
    },
    {
        "funcod": 714,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-26",
        "funsig": "SAFIM_FN_TAR_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR TAREA",
        "fecreg": "2014-03-26",
        "funnom": "LISTAR TAREA"
    },
    {
        "funcod": 715,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-26",
        "funsig": "SAFIM_FN_RUB_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR RUBRO",
        "fecreg": "2014-03-26",
        "funnom": "LISTAR RUBRO"
    },
    {
        "funcod": 1072,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-01",
        "funsig": "SISCOTI_FN_REGPOST                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR POSTULACION",
        "fecreg": "2014-10-01",
        "funnom": "REGISTRAR POSTULACION"
    },
    {
        "funcod": 1073,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-01",
        "funsig": "SISCOTI_FN_LISTUG                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR UNIDAD GESTION",
        "fecreg": "2014-09-08",
        "funnom": "LISTAR UNIDAD GESTION"
    },
    {
        "funcod": 1074,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-01",
        "funsig": "SISCOTI_FN_LISTPS                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR  PARAMETROS SISTEMA",
        "fecreg": "2014-09-09",
        "funnom": "LISTAR PARAMETROS SISTEMA"
    },
    {
        "funcod": 1075,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-10",
        "funsig": "SISCOTI_FN_REGDONDET                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR DETALLE DE DONACIÓN",
        "fecreg": "2014-09-10",
        "funnom": "REGISTRAR DETALLE DE DONACIÓN"
    },
    {
        "funcod": 1076,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-11",
        "funsig": "SISCOTI_FN_MODDON                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "MODIFICAR DONACION",
        "fecreg": "2014-09-11",
        "funnom": "MODIFICAR DONACION"
    },
    {
        "funcod": 1077,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-12",
        "funsig": "SISCOTI_FN_REGSUP                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR FICHA SUPERVISION",
        "fecreg": "2014-09-12",
        "funnom": "REGISTRAR FICHA SUPERVISION"
    },
    {
        "funcod": 1078,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-12",
        "funsig": "SISCOTI_FN_REGSUPDET                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR DETALLE DE SUPERVISION",
        "fecreg": "2014-09-12",
        "funnom": "REGISTRAR DETALLE DE SUPERVISION"
    },
    {
        "funcod": 1079,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-10",
        "funsig": "SISCOTI_FN_REGCON                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR CONVENIO",
        "fecreg": "2014-10-10",
        "funnom": "REGISTRAR CONVENIO"
    },
    {
        "funcod": 1080,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-10",
        "funsig": "SISCOTI_FN_REGINFCON                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR INFORME TECNICO CONVENIO",
        "fecreg": "2014-10-10",
        "funnom": "REGISTRAR INFORME TECNICO CONVENIO"
    },
    {
        "funcod": 1081,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-10",
        "funsig": "SISCOTI_FN_REGINFCON                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR INFORME SEGUIMIENTO",
        "fecreg": "2014-10-10",
        "funnom": "REGISTRAR INFORME SEGUIMIENTO"
    },
    {
        "funcod": 1082,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-10",
        "funsig": "SISCOTI_FN_REGSEG                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE REGISTRAR SEGUIMIENTO",
        "fecreg": "2014-10-10",
        "funnom": "REGISTRAR SEGUIMIENTO"
    },
    {
        "funcod": 1083,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-10",
        "funsig": "SISCOTI_FN_BUSSEG                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE BUSCAR SEGUIMIENTO",
        "fecreg": "2014-10-10",
        "funnom": "BUSCAR SEGUIMIENTO"
    },
    {
        "funcod": 1084,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-11",
        "funsig": "SISCOTI_FN_REGREVEXP                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR REVISION DE EXPEDIENTE",
        "fecreg": "2014-09-11",
        "funnom": "REGISTRAR REVISION DE EXPEDIENTE"
    },
    {
        "funcod": 1085,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-11",
        "funsig": "SISCOTI_FN_REGINFTEC                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR INFORME TECNICO",
        "fecreg": "2014-09-11",
        "funnom": "REGISTRAR INFORME TECNICO"
    },
    {
        "funcod": 1086,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-11",
        "funsig": "SISCOTI_FN_REGINFDET                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR INFORME TECNICO DETALLE",
        "fecreg": "2014-09-11",
        "funnom": "REGISTRAR INFORME TECNICO DETALLE"
    },
    {
        "funcod": 1087,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-08",
        "funsig": "SISCOTI_FN_REGDON                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRAR DONACIÓN",
        "fecreg": "2014-09-03",
        "funnom": "REGISTRAR DONACIÓN"
    },
    {
        "funcod": 1088,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-11",
        "funsig": "SISCOTI_FN_BUSDON                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "BUSCAR DONACIONES",
        "fecreg": "2014-09-11",
        "funnom": "BUSCAR DONACIONES"
    },
    {
        "funcod": 1089,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-14",
        "funsig": "SISCOTI_FN_CONDON                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR DONACION",
        "fecreg": "2014-09-14",
        "funnom": "CONSULTAR DONACION"
    },
    {
        "funcod": 1090,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-01",
        "funsig": "SISCOTI_FN_CONBEC                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR BECAS GESTIONADAS POR SCTI",
        "fecreg": "2014-10-01",
        "funnom": "CONSULTAR BECAS GESTIONADAS POR SCTI"
    },
    {
        "funcod": 1091,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-01",
        "funsig": "SISCOTI_FN_REPEJE                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR LA EJECUCION BECAS GESTIONADAS POR SCTI",
        "fecreg": "2014-10-01",
        "funnom": "REPORTE DE EJECUCION BECAS GESTIONADAS POR SCTI"
    },
    {
        "funcod": 1092,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-01",
        "funsig": "SISCOTI_FN_REGTALINT                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR REGISTRO DE TALLERES O INTERCAMBIOS DE EXPERIENCIAS",
        "fecreg": "2014-10-01",
        "funnom": "CONSULTAR REGISTRO DE TALLERES O INTERCAMBIOS DE E"
    },
    {
        "funcod": 1093,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-01",
        "funsig": "SISCOTI_FN_REPTALINT                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CONSULTAR REPORTE DE TALLERES O INTERCAMBIO DE EXPERIENCIAS REALIZADOS",
        "fecreg": "2014-10-01",
        "funnom": "CONSULTAR REPORTE DE TALLERES O INTERCAMBIO DE EXP"
    },
    {
        "funcod": 1555,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-28",
        "funsig": "SISPAN_FN_LISTLIQPAN                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "LIQUIDACION DE PANELES",
        "fecreg": "2015-10-28",
        "funnom": "LIQUIDACION DE PANELES"
    },
    {
        "funcod": 2640,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_CON_LISTADO_INFORME                      ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTA DE LISTADO DE INFORMES",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTA DE LISTADO DE INFORMES"
    },
    {
        "funcod": 271,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-07-31",
        "funsig": "JDC_FUN_BUSRESSAN                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE BUSCAR RESOLUCIONES DE SANCION",
        "fecreg": "2013-07-31",
        "funnom": "BUSCAR RESOLUCION SANCION"
    },
    {
        "funcod": 272,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-07-31",
        "funsig": "JDC_FUN_AGRRESSAN                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE AGREGAR RESOLUCIÓN DE SANCION",
        "fecreg": "2013-07-31",
        "funnom": "AGREGAR RESOLUCIÓN DE SANCION"
    },
    {
        "funcod": 273,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-07-31",
        "funsig": "JDC_FUN_ELIRESSAN                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR RESOLUCIÓN DE SANCION",
        "fecreg": "2013-07-31",
        "funnom": "ELIMINAR RESOLUCIÓN SANCION"
    },
    {
        "funcod": 361,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-09-13",
        "funsig": "JUDIC_FN_ELICAS                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE ELIMINAR EL CASO",
        "fecreg": "2013-09-13",
        "funnom": "ELIMINAR CASO"
    },
    {
        "funcod": 624,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-02-06",
        "funsig": "SAFIM_FN_ESP_LIS                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE LISTAR ESPECIFICA",
        "fecreg": "2014-02-06",
        "funnom": "LISTAR ESPECIFICA"
    },
    {
        "funcod": 625,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-02-06",
        "funsig": "SAFIM_FN_ESP_CON                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE OBTENER DATOS DE UNA ESPECIFICA",
        "fecreg": "2014-02-06",
        "funnom": "CONSULTA ESPECIFICA"
    },
    {
        "funcod": 711,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-25",
        "funsig": "SAFIM_FN_PEDBS_CRE                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "PERMITE CREAR PEDIDO DE BB SS",
        "fecreg": "2014-03-25",
        "funnom": "CREAR PEDIDO BB SS"
    },
    {
        "funcod": 1560,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_BUSCAR                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "BUSCAR"
    },
    {
        "funcod": 1561,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_EXPEXC                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "EXPORTAREXCEL"
    },
    {
        "funcod": 1562,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_SALIR                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "SALIR"
    },
    {
        "funcod": 1563,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_CANCELAR                                ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "CANCELAR"
    },
    {
        "funcod": 1564,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_EXPWOR                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "EXPORTARWORD"
    },
    {
        "funcod": 1565,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_REFRESH                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "REFRESCAR"
    },
    {
        "funcod": 1566,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_EXPPDF                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "EXPORTARPDF"
    },
    {
        "funcod": 1567,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_SEPARA                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "SEPARADOR"
    },
    {
        "funcod": 1570,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_MULTIM                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "MULTIMEDIA"
    },
    {
        "funcod": 1571,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_GRABAR                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "GRABAR"
    },
    {
        "funcod": 1572,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_GRAFICOS                                ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "GRAFICOS"
    },
    {
        "funcod": 1573,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_ELIMINAR                                ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "ELIMINAR"
    },
    {
        "funcod": 1574,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_MODIFICAR                               ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "MODIFICAR"
    },
    {
        "funcod": 1575,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-29",
        "funsig": "SISPAN_FN_NUEVO                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2015-10-29",
        "funnom": "NUEVO"
    },
    {
        "funcod": 2073,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-15",
        "funsig": "SW_RTINP_RNSTF09                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-15",
        "funnom": "RTI REGISTRO EL NRO DE SERIE - TUC FISICO"
    },
    {
        "funcod": 2135,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-04-20",
        "funsig": "SW_RTINP_ITNPL10                                  ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2016-04-20",
        "funnom": "RTI IMPRIME TUC - NO PLATAFORMA"
    },
    {
        "funcod": 2641,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_CON_INFORME                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTAR DETALLE DE INFORME",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTAR DETALLE DE INFORME"
    },
    {
        "funcod": 2642,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_MOD_INFORME                              ",
        "funest": "1",
        "usureg": null,
        "fundes": "EDICIÓN DE INFORME",
        "fecreg": "2016-09-21",
        "funnom": "EDICIÓN DE INFORME"
    },
    {
        "funcod": 2643,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "funsig": "SIRA_FUN_REG_RECOMENDACION                        ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGITRO DE RECOMENDACIÓN",
        "fecreg": "2016-09-21",
        "funnom": "REGITRO DE RECOMENDACIÓN"
    },
    {
        "funcod": 2644,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_RECOMENDACION                        ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTA DE RECOMENDACIÓN",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTA DE RECOMENDACIÓN"
    },
    {
        "funcod": 2645,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_MOD_RECOMENDACION                        ",
        "funest": "1",
        "usureg": null,
        "fundes": "EDICION DE RECOMENDACIÓN",
        "fecreg": "2016-09-21",
        "funnom": "EDICION DE RECOMENDACIÓN"
    },
    {
        "funcod": 2646,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_ASG_RECOMENDACION                        ",
        "funest": "1",
        "usureg": null,
        "fundes": "ASIGNACIÓN DE RECOMENDACIÓN",
        "fecreg": "2016-09-21",
        "funnom": "ASIGNACIÓN DE RECOMENDACIÓN"
    },
    {
        "funcod": 2647,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_REG_PLAN_ACCION                          ",
        "funest": "1",
        "usureg": null,
        "fundes": "REGISTRO DE PLAN DE ACCIÓN",
        "fecreg": "2016-09-21",
        "funnom": "REGISTRO DE PLAN DE ACCIÓN"
    },
    {
        "funcod": 2648,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_CON_PLAN_ACCION                          ",
        "funest": "1",
        "usureg": null,
        "fundes": "CONSULTA DE PLAN DE ACCÓN",
        "fecreg": "2016-09-21",
        "funnom": "CONSULTA DE PLAN DE ACCÓN"
    },
    {
        "funcod": 2649,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_MOD_PLAN_ACCION                          ",
        "funest": "1",
        "usureg": null,
        "fundes": "EDICIÓN DE PLAN DE ACCIÓN",
        "fecreg": "2016-09-21",
        "funnom": "EDICIÓN DE PLAN DE ACCIÓN"
    },
    {
        "funcod": 2650,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_APR_PLAN_ACCION                          ",
        "funest": "1",
        "usureg": null,
        "fundes": "APROBACIÓN DE PLAN DE ACCIÓN",
        "fecreg": "2016-09-21",
        "funnom": "APROBACIÓN DE PLAN DE ACCIÓN"
    },
    {
        "funcod": 2651,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "funsig": "SIRA_FUN_RPR_PLAN_ACCION                          ",
        "funest": "1",
        "usureg": null,
        "fundes": "REPROGRAMACIÓN DE PLAN DE ACCIÓN",
        "fecreg": "2016-09-21",
        "funnom": "REPROGRAMACIÓN DE PLAN DE ACCIÓN"
    },
    {
        "funcod": 3247,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-03-21",
        "funsig": "ELI_FICHA                                         ",
        "funest": "1",
        "usureg": null,
        "fundes": "ELIMINAR FICHA",
        "fecreg": "2017-03-21",
        "funnom": "ELIMINAR FICHA"
    },
    {
        "funcod": 4230,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-02-20",
        "funsig": "SW_RTINP_LB11                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-02-20",
        "funnom": "RTI LIBERAR RECIBO"
    },
    {
        "funcod": 4243,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-02-21",
        "funsig": "SW_RTINP_CP12                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-02-21",
        "funnom": "RTI CAMBIAR PROPIETARIO"
    },
    {
        "funcod": 4259,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-02-26",
        "funsig": "SW_RTINP_RRD13                                    ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-02-26",
        "funnom": "RTI REVERTIR RETIRO DEF"
    },
    {
        "funcod": 4264,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-02-27",
        "funsig": "SW_RTINP_MR14                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-02-27",
        "funnom": "RTI MODIFICAR RECIBO"
    },
    {
        "funcod": 4277,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-03-01",
        "funsig": "SW_RTINP_REGVEH16                                 ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-03-01",
        "funnom": "REGULARIZACIÓN VEHÍCULO"
    },
    {
        "funcod": 4351,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-03-19",
        "funsig": "SISCRE_CAMB_FEC                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "CAMBIAR FECHA VIGENCIA CREDENCIAL",
        "fecreg": "2018-03-19",
        "funnom": "CAMBIAR FECHA VIGENCIA"
    },
    {
        "funcod": 4520,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-05-17",
        "funsig": "SW_RTINP_PJ16                                     ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-05-17",
        "funnom": "RTI PERSONA JURIDICA"
    },
    {
        "funcod": 4548,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-05-28",
        "funsig": "SAFIM_FN_APROBADOR                                ",
        "funest": "1",
        "usureg": null,
        "fundes": "APROBAR LA PROGRAMACION PRESUPUESTAL",
        "fecreg": "2018-05-28",
        "funnom": "APROBADOR PROGRAMACION"
    },
    {
        "funcod": 4699,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-06-21",
        "funsig": "SISCRE_ANUL_CRE                                   ",
        "funest": "1",
        "usureg": null,
        "fundes": "ANULAR CREDENCIAL VIGENTE",
        "fecreg": "2018-06-21",
        "funnom": "ANULAR CREDENCIAL"
    },
    {
        "funcod": 4743,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-07-09",
        "funsig": "SW_RDCM_PJ17                                      ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-07-09",
        "funnom": "RTI RETIRO FRAUDE"
    },
    {
        "funcod": 4793,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-07-25",
        "funsig": "BAJA_BIEN                                         ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-07-25",
        "funnom": "BAJA DE BIEN"
    },
    {
        "funcod": 4877,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-09-04",
        "funsig": "DESINVENTARIAR                                    ",
        "funest": "1",
        "usureg": null,
        "fundes": null,
        "fecreg": "2018-09-04",
        "funnom": "DESINVENTARIAR"
    }];
  }
