import { Injectable } from '@angular/core';
import { Rol } from '../../models/rol';
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';
import { environment } from 'src/environments/environment';
import { HttpClient } from '@angular/common/http';

@Injectable({
  providedIn: 'root'
})
export class RolService {

  url: string = `${environment.HOST_URL}/roles`;  
  constructor(private http: HttpClient) { }
  
  listar() {
    return this.http.get<Rol[]>(this.url);
  }
  
  registrar(data: Rol) {
    return this.http.post(this.url, data);
  }
  
  modificar(data: Rol) {
    return this.http.put(this.url, data);
  }
  
  eliminar(id: number) {
    return this.http.delete(`${this.url}/${id}`);
  }

  getRoles(term: string = null): Observable<Rol[]> {
    let items = getlistaRoles();
    if (term) {
        items = items.filter(x => (x.rolnom.toLocaleLowerCase().indexOf(term.toLocaleLowerCase()) > -1));
    }
    return of(items).pipe(delay(500));
  }
}

function getlistaRoles() {
  return [
    {
        "rolcod": 44,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-05-28",
        "usureg": null,
        "fecreg": "2014-05-28",
        "rolnom": "CONSULTA",
        "rolsig": "CONSUL              ",
        "rolest": "1",
        "roldes": "CONSULTA REPORTES"
    },
    {
        "rolcod": 66,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-03-09",
        "usureg": null,
        "fecreg": "2016-03-09",
        "rolnom": "OPD",
        "rolsig": "ROL_OPD             ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 70,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-05-17",
        "usureg": null,
        "fecreg": "2016-05-04",
        "rolnom": "MASTER",
        "rolsig": "MAS                 ",
        "rolest": "1",
        "roldes": "MASTER"
    },
    {
        "rolcod": 71,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-06-06",
        "usureg": null,
        "fecreg": "2016-06-06",
        "rolnom": "ADMIN",
        "rolsig": "SISEDVIAL_ADMIN     ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 93,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-07",
        "usureg": null,
        "fecreg": "2017-11-23",
        "rolnom": "admin",
        "rolsig": "sinse_admin         ",
        "rolest": "1",
        "roldes": "TIENE ACCESO A TODOS LOS MODULOS "
    },
    {
        "rolcod": 94,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-11-27",
        "usureg": null,
        "fecreg": "2017-11-27",
        "rolnom": "especialista",
        "rolsig": "SISRU_ESPE          ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 95,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-07",
        "usureg": null,
        "fecreg": "2017-12-07",
        "rolnom": "grupo_sunarp",
        "rolsig": "grupo_sunarp        ",
        "rolest": "1",
        "roldes": "TIENE ACCESOS A TODOS LOS WEB SERVICES DE SUNARP"
    },
    {
        "rolcod": 96,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-07",
        "usureg": null,
        "fecreg": "2017-12-07",
        "rolnom": "grupo_mef",
        "rolsig": "grupo_mef           ",
        "rolest": "1",
        "roldes": "TIENE ACCESO A TODOS LOS SERVICIOS WEB DEL MEF"
    },
    {
        "rolcod": 97,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-07",
        "usureg": null,
        "fecreg": "2017-12-07",
        "rolnom": "grupo_inpe",
        "rolsig": "grupo_inpe          ",
        "rolest": "1",
        "roldes": "TIENE ACCESO A TODOS LOS SERVICIOS WEB DEL INPE"
    },
    {
        "rolcod": 98,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-07",
        "usureg": null,
        "fecreg": "2017-12-07",
        "rolnom": "grupo_judicial",
        "rolsig": "grupo_judicial      ",
        "rolest": "1",
        "roldes": "TIENE ACCESO A TODOS LOS SERVICIOS WEB DEL PODER JUDICIAL"
    },
    {
        "rolcod": 99,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-07",
        "usureg": null,
        "fecreg": "2017-12-07",
        "rolnom": "grupo_migraciones",
        "rolsig": "grupo_migraciones   ",
        "rolest": "1",
        "roldes": "TIENE ACCESO A TODOS LOS SERVICIOS WEB DE MIGRACIONES"
    },
    {
        "rolcod": 107,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-05-04",
        "usureg": null,
        "fecreg": "2018-05-04",
        "rolnom": "SUPER ADMNISTRADOR ",
        "rolsig": "PDMVAT_SUPER_ADMIN  ",
        "rolest": "1",
        "roldes": "SUPER ADMNISTRADOR "
    },
    {
        "rolcod": 108,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-05-04",
        "usureg": null,
        "fecreg": "2018-05-04",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "PDMVAT_ADMIN        ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR"
    },
    {
        "rolcod": 109,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-05-04",
        "usureg": null,
        "fecreg": "2018-05-04",
        "rolnom": "USUARIO",
        "rolsig": "PDMVAT_USUARIO      ",
        "rolest": "1",
        "roldes": "USUARIO"
    },
    {
        "rolcod": 111,
        "estreg": "0",
        "usumod": null,
        "fecmod": "2018-06-22",
        "usureg": null,
        "fecreg": "2018-06-22",
        "rolnom": "USER",
        "rolsig": "USER                ",
        "rolest": "1",
        "roldes": "user general"
    },
    {
        "rolcod": 112,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-06-22",
        "usureg": null,
        "fecreg": "2018-06-22",
        "rolnom": "user",
        "rolsig": "USER                ",
        "rolest": "1",
        "roldes": "user general"
    },
    {
        "rolcod": 116,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-07-30",
        "usureg": null,
        "fecreg": "2018-07-30",
        "rolnom": "MEDICO",
        "rolsig": "R_MEDICO            ",
        "rolest": "1",
        "roldes": "CONSULTORIO MEDICO"
    },
    {
        "rolcod": 118,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-07-31",
        "usureg": null,
        "fecreg": "2018-07-31",
        "rolnom": "POI",
        "rolsig": "SISREPGP_POI        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 25,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-07",
        "usureg": null,
        "fecreg": "2013-05-07",
        "rolnom": "ARCHIVO",
        "rolsig": "JUDIC_R_ARCH        ",
        "rolest": "1",
        "roldes": "ALMACENAN DOCUMENTOS"
    },
    {
        "rolcod": 28,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-16",
        "usureg": null,
        "fecreg": "2013-05-16",
        "rolnom": "PROCURADOR",
        "rolsig": "JUDIC_PROCURADOR    ",
        "rolest": "1",
        "roldes": "PROCURADOR"
    },
    {
        "rolcod": 30,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-07-01",
        "usureg": null,
        "fecreg": "2013-07-01",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "ACSE_ROL_ADMIN      ",
        "rolest": "1",
        "roldes": "CONTROL TOTAL DEL SISTEMA DE SEGURIDAD"
    },
    {
        "rolcod": 31,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-07-01",
        "usureg": null,
        "fecreg": "2013-07-01",
        "rolnom": "USUARIO",
        "rolsig": "ACSE_ROL_USUA       ",
        "rolest": "1",
        "roldes": "CONTROL SOLO DE SISTEMAS ASIGNADOS"
    },
    {
        "rolcod": 26,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-13",
        "usureg": null,
        "fecreg": "2013-05-13",
        "rolnom": "SECRETARIA",
        "rolsig": "JUDIC_SECR          ",
        "rolest": "1",
        "roldes": "PERFIL PARA SECRETARIAS"
    },
    {
        "rolcod": 27,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-13",
        "usureg": null,
        "fecreg": "2013-05-13",
        "rolnom": "ASISTENTE DE PROCURADURIA",
        "rolsig": "JUDIC_ASIS          ",
        "rolest": "1",
        "roldes": "ASISTENTE DE PROCURADURIA"
    },
    {
        "rolcod": 29,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-05-24",
        "usureg": null,
        "fecreg": "2013-05-24",
        "rolnom": "CONSULTA",
        "rolsig": "JUDIC_R_VISITA      ",
        "rolest": "1",
        "roldes": "SOLO PUEDE CONSULTAR DATOS"
    },
    {
        "rolcod": 4,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-01-30",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "SIAM_R_ADMIN        ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR"
    },
    {
        "rolcod": 14,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-02-19",
        "rolnom": "PRACTICANTE",
        "rolsig": "SGRS_PRACTICANTE    ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 16,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-02-19",
        "rolnom": "ABOGADO",
        "rolsig": "SGRS_ABOGADO        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 17,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-02-19",
        "rolnom": "PROFESIONAL TECNICO",
        "rolsig": "SGRS_PROFTEC        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 18,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-02-20",
        "rolnom": "ADMINISTRADOR SISACI",
        "rolsig": "SISACI_ADMIN        ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR DEL SISTEMA DE ADJUDICACION DE CORREDORES"
    },
    {
        "rolcod": 1,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-01-30",
        "usureg": null,
        "fecreg": "2013-01-28",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "SISPLA_R_ADMIN      ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR DEL SISTEMA DE PLANEAMIENTO"
    },
    {
        "rolcod": 5,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-01-31",
        "rolnom": "ADMINISTRADOR SIT",
        "rolsig": "SIGERE_R_ADMIN_SIT  ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR SIT DEL SIGERE"
    },
    {
        "rolcod": 6,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-01-31",
        "rolnom": "ADMINISTRADOR SRT",
        "rolsig": "SIGERE_R_ADMIN_SRT  ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR SRT DEL SIGERE"
    },
    {
        "rolcod": 8,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-01-31",
        "rolnom": "ENCARGADO AREA SRT",
        "rolsig": "SIGERE_R_AREA_SRT   ",
        "rolest": "1",
        "roldes": "ENCARGADO DE AREA SRT"
    },
    {
        "rolcod": 10,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-01-31",
        "rolnom": "ENCARGADO IMPRESION SRT",
        "rolsig": "SIGERE_R_IMP_SRT    ",
        "rolest": "1",
        "roldes": "ENCARGADO IMPRESION SRT"
    },
    {
        "rolcod": 9,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-01-31",
        "rolnom": "EVALUADOR LEGAL SRT",
        "rolsig": "SIGERE_R_LEGAL      ",
        "rolest": "1",
        "roldes": "EVALUADOR LEGAL SRT"
    },
    {
        "rolcod": 7,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-01-31",
        "rolnom": "OPERADOR SRT",
        "rolsig": "SIGERE_R_OPE_SRT    ",
        "rolest": "1",
        "roldes": "EVALUADOR LEGAL SRT"
    },
    {
        "rolcod": 11,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-01-31",
        "rolnom": "OPERADOR SIT",
        "rolsig": "SIGERE_R_OPE_SIT    ",
        "rolest": "1",
        "roldes": "EVALUADOR LEGAL SRT"
    },
    {
        "rolcod": 12,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": "1",
        "fecreg": "2013-01-31",
        "rolnom": "VERIFICADOR SIT",
        "rolsig": "SIGERE_R_VER_SIT    ",
        "rolest": "1",
        "roldes": "EVALUADOR LEGAL SRT"
    },
    {
        "rolcod": 23,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-03-26",
        "usureg": null,
        "fecreg": "2013-03-26",
        "rolnom": "MESA DE PARTES",
        "rolsig": "JUDIC_R_MEPA        ",
        "rolest": "1",
        "roldes": "ENCARGADO DE LA MANIPULACIÓN DE DATOS"
    },
    {
        "rolcod": 24,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-03-26",
        "usureg": null,
        "fecreg": "2013-03-26",
        "rolnom": "ABOGADO",
        "rolsig": "JUDIC_R_ABOG        ",
        "rolest": "1",
        "roldes": "REALIZA CONSULTAS CON LA INFORMACIÓN QUE ESTA ALMACENADA EN EL SISTEMA"
    },
    {
        "rolcod": 2,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-01-30",
        "usureg": null,
        "fecreg": "2013-01-28",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "SISLIC_R_ADMIN      ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR DEL SISTEMA DE LICENCIAS"
    },
    {
        "rolcod": 3,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-01-30",
        "usureg": null,
        "fecreg": "2013-01-30",
        "rolnom": "ASISTENTE",
        "rolsig": "SISPLA_R_ASISTENTE  ",
        "rolest": "1",
        "roldes": "REALIZA LAS OPERACIOENS DE UN ASISITENTE DE GERENCIA"
    },
    {
        "rolcod": 15,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-02-19",
        "rolnom": "ADMINISTRADOR DE SISTEMA",
        "rolsig": "SGRS_ADMINSIS       ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 13,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-02-07",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "JUDIC_R_ADMIN       ",
        "rolest": "1",
        "roldes": "ENCARGADO DE LA ADMINISTRACIÓN DEL SISTEMA"
    },
    {
        "rolcod": 19,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-03",
        "usureg": null,
        "fecreg": "2013-02-22",
        "rolnom": "SUBGERENTE DE EVALUACIÓN Y CALIDAD AMBIENTAL",
        "rolsig": "SGRS_SUBGER         ",
        "rolest": "1",
        "roldes": "SUBGERENTE DE EVALUACIÓN Y CALIDAD AMBIENTAL"
    },
    {
        "rolcod": 20,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-02-22",
        "rolnom": "SECRETARIA",
        "rolsig": "SGRS_SECRE          ",
        "rolest": "1",
        "roldes": "SECRETARIA"
    },
    {
        "rolcod": 21,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-02-22",
        "rolnom": "JEFE DE DIVISIÓN",
        "rolsig": "SGRS_JEFDIV         ",
        "rolest": "1",
        "roldes": "JEFE DE DIVISIÓN"
    },
    {
        "rolcod": 22,
        "estreg": "1",
        "usumod": null,
        "fecmod": null,
        "usureg": null,
        "fecreg": "2013-02-22",
        "rolnom": "COORDINADOR",
        "rolsig": "SGRS_COORDI         ",
        "rolest": "1",
        "roldes": "COORDINADOR"
    },
    {
        "rolcod": 36,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-11-04",
        "usureg": null,
        "fecreg": "2013-11-04",
        "rolnom": "SECRETARIA SGMA",
        "rolsig": "SGRS_SECRE_SGMA     ",
        "rolest": "1",
        "roldes": "SECRETARIA DE LA SUBGERENCIA DE MEDIO AMBIENTE"
    },
    {
        "rolcod": 37,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-12-06",
        "usureg": null,
        "fecreg": "2013-12-06",
        "rolnom": "CONSULTA PLANILLA",
        "rolsig": "SAFIM_CONSUL        ",
        "rolest": "1",
        "roldes": "SOLO CONSULTA DATOS DE PLANILLA"
    },
    {
        "rolcod": 38,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-02",
        "usureg": null,
        "fecreg": "2014-01-02",
        "rolnom": "Administrador de Sistema",
        "rolsig": "SAFIM_R_ADMINSIS    ",
        "rolest": "1",
        "roldes": "Administra el sistema SAFIM"
    },
    {
        "rolcod": 41,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-02-10",
        "usureg": null,
        "fecreg": "2014-02-10",
        "rolnom": "CONTABILIDAD CATALOGO",
        "rolsig": "SAFIM_R_CONTAB_CAT  ",
        "rolest": "1",
        "roldes": "MANTENIMIENTO AL CATALOGO POR PARTE DEL ÁREA DE CONTABILIDAD"
    },
    {
        "rolcod": 53,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-09-02",
        "usureg": null,
        "fecreg": "2015-09-02",
        "rolnom": "OPERADOR",
        "rolsig": "LCVM_OPERADOR       ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 54,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-26",
        "usureg": null,
        "fecreg": "2015-10-22",
        "rolnom": "DIGITADOR",
        "rolsig": "SISPAN_DIG          ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 57,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-26",
        "usureg": null,
        "fecreg": "2015-10-26",
        "rolnom": "SUPERVISOR",
        "rolsig": "SISPAN_SUPERVISOR   ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 65,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-03-07",
        "usureg": null,
        "fecreg": "2016-03-07",
        "rolnom": " Operador",
        "rolsig": "CONSWEB_OPERADOR    ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 68,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-03-17",
        "usureg": null,
        "fecreg": "2016-03-17",
        "rolnom": "ADMIN",
        "rolsig": "SIDU_ADMIN          ",
        "rolest": "1",
        "roldes": "ADMI"
    },
    {
        "rolcod": 69,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-27",
        "usureg": null,
        "fecreg": "2016-04-19",
        "rolnom": "administrador",
        "rolsig": "SISSRU_ADMIN        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 78,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "usureg": null,
        "fecreg": "2016-09-21",
        "rolnom": "MONITOR",
        "rolsig": "SIRA_R_MONITOR      ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 79,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-11-22",
        "usureg": null,
        "fecreg": "2016-09-27",
        "rolnom": "SUPERVISOR",
        "rolsig": "SISCPA_SUPER        ",
        "rolest": "1",
        "roldes": "SUPERVISOR DE INVENTARIO"
    },
    {
        "rolcod": 80,
        "estreg": "0",
        "usumod": null,
        "fecmod": "2016-09-27",
        "usureg": null,
        "fecreg": "2016-09-27",
        "rolnom": "INVENTARIADOR",
        "rolsig": "SISCPA_INVEN        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 81,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-27",
        "usureg": null,
        "fecreg": "2016-09-27",
        "rolnom": "INVENTARIADOR",
        "rolsig": "SISCPA_INVEN        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 88,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-01-15",
        "usureg": null,
        "fecreg": "2017-05-17",
        "rolnom": "OPERADOR_PLATAFORMA_IND",
        "rolsig": "SITUPOE             ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 90,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-08-01",
        "usureg": null,
        "fecreg": "2017-08-01",
        "rolnom": "PROVISIONAL",
        "rolsig": "ROL_PROV            ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 101,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-15",
        "usureg": null,
        "fecreg": "2017-12-15",
        "rolnom": "grupo_sunat",
        "rolsig": "grupo_sunat         ",
        "rolest": "1",
        "roldes": "ACCESO AL SERVICIO SUNAT"
    },
    {
        "rolcod": 102,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-15",
        "usureg": null,
        "fecreg": "2017-12-15",
        "rolnom": "grupo_minedu",
        "rolsig": "grupo_minedu        ",
        "rolest": "1",
        "roldes": "ACCESOS AL SERVICIO MINEDU"
    },
    {
        "rolcod": 117,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-07-31",
        "usureg": null,
        "fecreg": "2018-07-31",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "SISREPGP_ADMIN      ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 32,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-09-12",
        "usureg": null,
        "fecreg": "2013-09-12",
        "rolnom": "RECEPCIONISTA",
        "rolsig": "REC                 ",
        "rolest": "1",
        "roldes": "RECEPCIONISTA DE SOLICITUD"
    },
    {
        "rolcod": 33,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-09-12",
        "usureg": null,
        "fecreg": "2013-09-12",
        "rolnom": "FILIADOR",
        "rolsig": "FIL                 ",
        "rolest": "1",
        "roldes": "FILIADOR DE CITAS EN LINEA"
    },
    {
        "rolcod": 34,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-09-12",
        "usureg": null,
        "fecreg": "2013-09-12",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "ADMIN               ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR SICASA"
    },
    {
        "rolcod": 39,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-20",
        "usureg": null,
        "fecreg": "2014-01-20",
        "rolnom": "CATALOGADOR",
        "rolsig": "SAFIM_R_CATAL       ",
        "rolest": "1",
        "roldes": "DA MANTENIMIENTO AL CATALOGO"
    },
    {
        "rolcod": 55,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-22",
        "usureg": null,
        "fecreg": "2015-10-22",
        "rolnom": "ADMINITRADOR",
        "rolsig": "SISPAN_ADMIN        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 58,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-11-24",
        "usureg": null,
        "fecreg": "2015-11-24",
        "rolnom": "OPERADOR",
        "rolsig": "DCE_OPE             ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 59,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-02-19",
        "usureg": null,
        "fecreg": "2015-12-15",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "SITU_DCE_ADMIN      ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 60,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-01-26",
        "usureg": null,
        "fecreg": "2016-01-26",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "SISCONPA_ADMIN      ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 62,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-02-19",
        "usureg": null,
        "fecreg": "2016-02-19",
        "rolnom": "SUPERVISOR",
        "rolsig": "SITU_DCE_SUPER      ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 63,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-02-19",
        "usureg": null,
        "fecreg": "2016-02-19",
        "rolnom": "DIGITADOR",
        "rolsig": "SITU_DCE_DIGI       ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 72,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-07-27",
        "usureg": null,
        "fecreg": "2016-07-27",
        "rolnom": "ADMINISTRADOR DEL SISTEMA",
        "rolsig": "SISCPA_ADMIN        ",
        "rolest": "1",
        "roldes": "Administrador del sistema SISCPA"
    },
    {
        "rolcod": 75,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "usureg": null,
        "fecreg": "2016-09-21",
        "rolnom": "APROBADOR",
        "rolsig": "SIRA_R_APRO         ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 86,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-12-21",
        "usureg": null,
        "fecreg": "2016-12-21",
        "rolnom": "OPERADOR UNICA",
        "rolsig": "OPEU                ",
        "rolest": "1",
        "roldes": "OPERADOR UNICA"
    },
    {
        "rolcod": 110,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-05-22",
        "usureg": null,
        "fecreg": "2018-05-22",
        "rolnom": "CONSULTA",
        "rolsig": "SISCPA_CONSULTA     ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 113,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-07-11",
        "usureg": null,
        "fecreg": "2018-07-11",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "IN_ADMIN            ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 114,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-07-30",
        "usureg": null,
        "fecreg": "2018-07-30",
        "rolnom": "ADMISION",
        "rolsig": "R_ADMISION          ",
        "rolest": "1",
        "roldes": "RESPONSABLE DE ADMISION "
    },
    {
        "rolcod": 115,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-07-30",
        "usureg": null,
        "fecreg": "2018-07-30",
        "rolnom": "ENFERMERIA",
        "rolsig": "R_ENFERMERIA        ",
        "rolest": "1",
        "roldes": "TRIAJE ENFERMERIA Y CONSULTAS"
    },
    {
        "rolcod": 43,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-03-07",
        "usureg": null,
        "fecreg": "2014-03-07",
        "rolnom": "OPERADOR",
        "rolsig": "OPE                 ",
        "rolest": "1",
        "roldes": "REGISTRAR TRANSACCIONES DEL SISTEMA"
    },
    {
        "rolcod": 46,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-16",
        "usureg": null,
        "fecreg": "2014-09-16",
        "rolnom": "JEFATURA",
        "rolsig": "SISCOTI_R_JEFATURA  ",
        "rolest": "1",
        "roldes": "JEFATURA"
    },
    {
        "rolcod": 47,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-16",
        "usureg": null,
        "fecreg": "2014-09-16",
        "rolnom": "SUBGERENCIA",
        "rolsig": "SISCOTI_R_SUBGERENCI",
        "rolest": "1",
        "roldes": "SUBGERENCIA"
    },
    {
        "rolcod": 48,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-09-03",
        "usureg": null,
        "fecreg": "2014-09-03",
        "rolnom": "OPERADOR",
        "rolsig": "SISCOTI_ROL_SISOPE  ",
        "rolest": "1",
        "roldes": "OPERADOR DEL SISTEMA"
    },
    {
        "rolcod": 49,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-17",
        "usureg": null,
        "fecreg": "2014-10-17",
        "rolnom": "DONACIONES",
        "rolsig": "SISCOTI_R_DONACIONES",
        "rolest": "1",
        "roldes": "DONACIONES"
    },
    {
        "rolcod": 50,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-17",
        "usureg": null,
        "fecreg": "2014-10-17",
        "rolnom": "BECAS",
        "rolsig": "SISCOTI_R_BECAS     ",
        "rolest": "1",
        "roldes": "BECAS"
    },
    {
        "rolcod": 51,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-10-17",
        "usureg": null,
        "fecreg": "2014-10-17",
        "rolnom": "CONVENIOS",
        "rolsig": "SISCOTI_R_CONVENIO  ",
        "rolest": "1",
        "roldes": "CONVENIOS"
    },
    {
        "rolcod": 52,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-09-02",
        "usureg": null,
        "fecreg": "2015-09-01",
        "rolnom": "Operador",
        "rolsig": "ALOGTU_OPERADOR     ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 56,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2015-10-23",
        "usureg": null,
        "fecreg": "2015-10-23",
        "rolnom": "MESA PARTE 2",
        "rolsig": null,
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 73,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-20",
        "usureg": null,
        "fecreg": "2016-09-20",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "SIRA_R_ADMINISTRADOR",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 74,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-20",
        "usureg": null,
        "fecreg": "2016-09-20",
        "rolnom": "COORDINADOR",
        "rolsig": "SIRA_R_COORDINADOR  ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 76,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "usureg": null,
        "fecreg": "2016-09-21",
        "rolnom": "VISOR",
        "rolsig": "SIRA_R_VIS          ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 77,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-09-21",
        "usureg": null,
        "fecreg": "2016-09-21",
        "rolnom": "REGISTRO",
        "rolsig": "SIRA_R_REG          ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 83,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-11-22",
        "usureg": null,
        "fecreg": "2016-11-22",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "AFPNET_ADMIN        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 89,
        "estreg": "0",
        "usumod": null,
        "fecmod": "2018-05-22",
        "usureg": null,
        "fecreg": "2017-08-01",
        "rolnom": "CONSULTA",
        "rolsig": "ROL_CONSULTA        ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 91,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-06-25",
        "usureg": null,
        "fecreg": "2017-11-07",
        "rolnom": "ADMIN",
        "rolsig": "ADMIN               ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR SPHU Y SAU"
    },
    {
        "rolcod": 92,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-11-07",
        "usureg": null,
        "fecreg": "2017-11-07",
        "rolnom": "grupo_sphu",
        "rolsig": "SPHU                ",
        "rolest": "1",
        "roldes": "ADMINISTRADOR SPHU"
    },
    {
        "rolcod": 103,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-01-15",
        "usureg": null,
        "fecreg": "2018-01-15",
        "rolnom": "OPERADOR_PLATAFORMA_REMISSE",
        "rolsig": "SITU_OPEREMIS       ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 104,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-03-12",
        "usureg": null,
        "fecreg": "2018-03-12",
        "rolnom": "admin_asocom",
        "rolsig": "admin_asocom        ",
        "rolest": "1",
        "roldes": "tiene todos los permisos"
    },
    {
        "rolcod": 35,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2013-09-12",
        "usureg": null,
        "fecreg": "2013-09-12",
        "rolnom": "SOPORTE",
        "rolsig": "ACSE_ROL_SOPO       ",
        "rolest": "1",
        "roldes": "PERMITE REALIZAR OPERACIONES COTIDIANAS"
    },
    {
        "rolcod": 40,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-01-28",
        "usureg": null,
        "fecreg": "2014-01-28",
        "rolnom": "CONSULTA CATALOGO",
        "rolsig": "SAFIM_R_CONS_CATA   ",
        "rolest": "1",
        "roldes": "PUEDE CONSULTAR EL CATALOGO"
    },
    {
        "rolcod": 42,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-02-20",
        "usureg": null,
        "fecreg": "2014-02-20",
        "rolnom": "ANALISTA",
        "rolsig": "SAFIM_R_ANALI       ",
        "rolest": "1",
        "roldes": "ANALISTA"
    },
    {
        "rolcod": 45,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2014-08-04",
        "usureg": null,
        "fecreg": "2014-08-04",
        "rolnom": "Consulta",
        "rolsig": "SISCS_ROL_CONSULTA  ",
        "rolest": "1",
        "roldes": "Usuario solo de consulta"
    },
    {
        "rolcod": 61,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-02-02",
        "usureg": null,
        "fecreg": "2016-02-02",
        "rolnom": "REQUERIMIENTO Y NOTAS",
        "rolsig": "SAFIM_R_REQNOTAS    ",
        "rolest": "1",
        "roldes": "GENERAR REQUERIMIENTO DE GASTO Y NOTAS DE MODIFICACIÓN"
    },
    {
        "rolcod": 64,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-03-07",
        "usureg": null,
        "fecreg": "2016-03-07",
        "rolnom": "PROGRAMACION_PRESPUESTO",
        "rolsig": "SAFIM_FN_PROG_PPTO  ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 67,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-03-14",
        "usureg": null,
        "fecreg": "2016-03-14",
        "rolnom": "Consultas",
        "rolsig": "CONSWEB-CONSULTA    ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 82,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-10-11",
        "usureg": null,
        "fecreg": "2016-10-11",
        "rolnom": "MASTER",
        "rolsig": "MASTER              ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 85,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2016-12-12",
        "usureg": null,
        "fecreg": "2016-12-12",
        "rolnom": "OPERADOR",
        "rolsig": "AFPNET_OPE          ",
        "rolest": "1",
        "roldes": "OPERADOR CAS"
    },
    {
        "rolcod": 87,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-01-11",
        "usureg": null,
        "fecreg": "2017-01-11",
        "rolnom": "MEDIDA PRECAUTORIA",
        "rolsig": "SITU_MEDIDA         ",
        "rolest": "1",
        "roldes": "MEDIDA PRECAUTORIA"
    },
    {
        "rolcod": 100,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2017-12-15",
        "usureg": null,
        "fecreg": "2017-12-15",
        "rolnom": "grupo_reniec",
        "rolsig": "grupo_reniec        ",
        "rolest": "1",
        "roldes": "ACCESO A LOS SERVICIOS DE RENIEC"
    },
    {
        "rolcod": 105,
        "estreg": "0",
        "usumod": null,
        "fecmod": "2018-05-22",
        "usureg": null,
        "fecreg": "2018-03-14",
        "rolnom": "CONSULTA_BIENES",
        "rolsig": "ROL_CONSULTA_BIENES ",
        "rolest": "1",
        "roldes": null
    },
    {
        "rolcod": 106,
        "estreg": "1",
        "usumod": null,
        "fecmod": "2018-04-06",
        "usureg": null,
        "fecreg": "2018-04-06",
        "rolnom": "ADMINISTRADOR",
        "rolsig": "R_ADMIN             ",
        "rolest": "1",
        "roldes": null
    }];
  }
