import { Injectable } from '@angular/core';
import { environment } from 'src/environments/environment';
import { HttpClient } from '@angular/common/http';
import { RolMenu } from '../../models/rolMenu';
import { SistemaRolDTO } from '../../models/sistemaRolDTO';
import { RolMenuDTO } from 'src/app/models/rolmenuDTO';

@Injectable({
  providedIn: 'root'
})
export class RolMenService {

  url: string = `${environment.HOST_URL}/rolesMenus`;  
  constructor(private http: HttpClient) { }
   
  listar() {
    return this.http.get<RolMenu[]>(this.url);
  }

  registrar(data: RolMenuDTO) {
    return this.http.post(this.url, data);
  }

  listarSistemaRol() {
    return this.http.get<SistemaRolDTO[]>(`${this.url}/listarSisRol`);
  }
  
  eliminar(id: number) {
    return this.http.delete(`${this.url}/${id}`);
  }


//   getMenusRoles(term: string = null): Observable<RolMenu[]> {
//     let items = getlistaMenuRol();
//     if (term) {
//         items = items.filter(x => (x.rol.rolnom.toLocaleLowerCase().indexOf(term.toLocaleLowerCase()) > -1));
//     }
//     return of(items).pipe(delay(500));
//   }
}

function getlistaMenuRol() {
  return [
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": null,
            "mencod": 26,
            "estreg": "1",
            "menest": "1",
            "menrut": null,
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": "2013-02-07",
            "mennom": "Parametros",
            "menpadflg": "1",
            "menord": 0,
            "mensig": "JUDIC_MP_PARAMETROS ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": null,
            "mencod": 24,
            "estreg": "1",
            "menest": "1",
            "menrut": null,
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": "2013-02-07",
            "mennom": "Proceso",
            "menpadflg": "1",
            "menord": 1,
            "mensig": "JUDIC_MP_PROCESO    ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 24,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Proceso",
                "menpadflg": "1",
                "menord": 1,
                "mensig": "JUDIC_MP_PROCESO    ",
                "menico": null
            },
            "mencod": 42,
            "estreg": "1",
            "menest": "0",
            "menrut": "~/WebApp/Procesos/JDC_ReasignarAbogado.aspx",
            "usureg": null,
            "fecreg": "2013-02-08",
            "usumod": null,
            "fecmod": "2013-06-14",
            "mennom": "Casos",
            "menpadflg": "0",
            "menord": 0,
            "mensig": "JUDIC_MH_CASOS      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": null,
            "mencod": 43,
            "estreg": "1",
            "menest": "1",
            "menrut": null,
            "usureg": null,
            "fecreg": "2013-02-08",
            "usumod": null,
            "fecmod": null,
            "mennom": "Consultas y Reportes",
            "menpadflg": "1",
            "menord": 2,
            "mensig": "JUDIC_MH_CONREP     ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 43,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-08",
                "usumod": null,
                "fecmod": null,
                "mennom": "Consultas y Reportes",
                "menpadflg": "1",
                "menord": 2,
                "mensig": "JUDIC_MH_CONREP     ",
                "menico": null
            },
            "mencod": 44,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Reportes/Reporte_Modelo.aspx",
            "usureg": null,
            "fecreg": "2013-02-08",
            "usumod": null,
            "fecmod": null,
            "mennom": "Civil, Laboral,Adm, Constitucional",
            "menpadflg": "0",
            "menord": 0,
            "mensig": "JUDIC_MH_CLAC       ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 43,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-08",
                "usumod": null,
                "fecmod": null,
                "mennom": "Consultas y Reportes",
                "menpadflg": "1",
                "menord": 2,
                "mensig": "JUDIC_MH_CONREP     ",
                "menico": null
            },
            "mencod": 45,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Reportes/Reporte_Modelo2.aspx",
            "usureg": null,
            "fecreg": "2013-02-08",
            "usumod": null,
            "fecmod": null,
            "mennom": "Penal",
            "menpadflg": "0",
            "menord": 1,
            "mensig": "JUDIC_MH_PENAL      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 27,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JUD_Cuaderno.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": "2013-02-07",
            "mennom": "Cuadernos",
            "menpadflg": "0",
            "menord": 0,
            "mensig": "JUDIC_MH_CUADE      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 29,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Autoridad.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Autoridades",
            "menpadflg": "0",
            "menord": 2,
            "mensig": "JUDIC_MH_AUTOR      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 30,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Materia.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Materias",
            "menpadflg": "0",
            "menord": 3,
            "mensig": "JUDIC_MH_MATER      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 31,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Via.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Vias",
            "menpadflg": "0",
            "menord": 4,
            "mensig": "JUDIC_MH_VIAS       ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 32,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Proceso.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Procesos",
            "menpadflg": "0",
            "menord": 5,
            "mensig": "JUDIC_MH_PROCESOS   ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 33,
            "estreg": "1",
            "menest": "0",
            "menrut": "~/WebApp/Mantenimientos/JDC_Asunto.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": "2013-07-08",
            "mennom": "Asunto",
            "menpadflg": "0",
            "menord": 6,
            "mensig": "JUDIC_MH_ASUNTO     ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 34,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Abogado.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Abogados",
            "menpadflg": "0",
            "menord": 7,
            "mensig": "JUDIC_MH_ABOGAD     ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 35,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Litigante.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Litigantes",
            "menpadflg": "0",
            "menord": 8,
            "mensig": "JUDIC_MH_LIT        ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 36,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_DelitoGenerico.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Delito Generico",
            "menpadflg": "0",
            "menord": 9,
            "mensig": "JUDIC_MH_DGENE      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 37,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_DelitoEspecifico.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Delito Especifico",
            "menpadflg": "0",
            "menord": 10,
            "mensig": "JUDIC_MH_DESPE      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 38,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Receptor.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Receptores",
            "menpadflg": "0",
            "menord": 11,
            "mensig": "JUDIC_MH_RECEP      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 39,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Giro.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Giros",
            "menpadflg": "0",
            "menord": 12,
            "mensig": "JUDIC_MH_GIROS      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 40,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_Tb_Estado.aspX",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Estados",
            "menpadflg": "0",
            "menord": 12,
            "mensig": "JUDIC_MH_ESTADOS    ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 26,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": "2013-02-07",
                "mennom": "Parametros",
                "menpadflg": "1",
                "menord": 0,
                "mensig": "JUDIC_MP_PARAMETROS ",
                "menico": null
            },
            "mencod": 41,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Mantenimientos/JDC_TipoCambio.aspx",
            "usureg": null,
            "fecreg": "2013-02-07",
            "usumod": null,
            "fecmod": null,
            "mennom": "Tipo Cambio",
            "menpadflg": "0",
            "menord": 12,
            "mensig": "JUDIC_MH_TIPCAM     ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 43,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-08",
                "usumod": null,
                "fecmod": null,
                "mennom": "Consultas y Reportes",
                "menpadflg": "1",
                "menord": 2,
                "mensig": "JUDIC_MH_CONREP     ",
                "menico": null
            },
            "mencod": 113,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Reportes/Reporte_Resumen_Casos.aspx",
            "usureg": null,
            "fecreg": "2013-12-04",
            "usumod": null,
            "fecmod": "2013-12-04",
            "mennom": "Resumen de Casos",
            "menpadflg": "0",
            "menord": 5,
            "mensig": "JUDIC_MH_RESCAS     ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 43,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-08",
                "usumod": null,
                "fecmod": null,
                "mennom": "Consultas y Reportes",
                "menpadflg": "1",
                "menord": 2,
                "mensig": "JUDIC_MH_CONREP     ",
                "menico": null
            },
            "mencod": 126,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Reportes/Reporte_Cambio_Estado.aspx",
            "usureg": null,
            "fecreg": "2014-02-20",
            "usumod": null,
            "fecmod": "2014-02-20",
            "mennom": "Cambio de Estado",
            "menpadflg": "0",
            "menord": 6,
            "mensig": "JUDIC_MH_CAMEST     ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 43,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-08",
                "usumod": null,
                "fecmod": null,
                "mennom": "Consultas y Reportes",
                "menpadflg": "1",
                "menord": 2,
                "mensig": "JUDIC_MH_CONREP     ",
                "menico": null
            },
            "mencod": 187,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Reportes/Reporte_Cambio_Gestion.aspx",
            "usureg": null,
            "fecreg": "2014-11-25",
            "usumod": null,
            "fecmod": "2014-11-26",
            "mennom": "Reporte de Transferencia",
            "menpadflg": "0",
            "menord": 7,
            "mensig": "JUDIC_MH_CAMGES     ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 43,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-08",
                "usumod": null,
                "fecmod": null,
                "mennom": "Consultas y Reportes",
                "menpadflg": "1",
                "menord": 2,
                "mensig": "JUDIC_MH_CONREP     ",
                "menico": null
            },
            "mencod": 253,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Reportes/Reporte_ModeloMP.aspx",
            "usureg": null,
            "fecreg": "2015-10-23",
            "usumod": null,
            "fecmod": "2015-10-23",
            "mennom": "REPORTE MESA PARTE",
            "menpadflg": "0",
            "menord": 1,
            "mensig": "JUDIC_MH_REPMP      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 43,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-08",
                "usumod": null,
                "fecmod": null,
                "mennom": "Consultas y Reportes",
                "menpadflg": "1",
                "menord": 2,
                "mensig": "JUDIC_MH_CONREP     ",
                "menico": null
            },
            "mencod": 494,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Reportes/Reporte_Demandas.aspx",
            "usureg": null,
            "fecreg": "2017-01-03",
            "usumod": null,
            "fecmod": "2017-01-23",
            "mennom": "Reporte Demandas",
            "menpadflg": "0",
            "menord": 8,
            "mensig": "JUDIC_DEMANDAS      ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    },
    {
        "rol": {
            "rolcod": 70,
            "estreg": "1",
            "usureg": null,
            "fecreg": "2016-05-04",
            "usumod": null,
            "fecmod": "2016-05-17",
            "rolest": "1",
            "rolsig": "MAS                 ",
            "rolnom": "MASTER",
            "roldes": "MASTER"
        },
        "menu": {
            "sistema": {
                "siscod": 5,
                "sissig": "JUDIC     ",
                "sisnom": "SISTEMA JUDICIAL",
                "sisest": "1",
                "sisdes": "SISTEMA PARA CASOS LEGALES",
                "estreg": "1",
                "usureg": null,
                "fecreg": "2013-02-07",
                "usumod": null,
                "fecmod": null
            },
            "padre": {
                "sistema": {
                    "siscod": 5,
                    "sissig": "JUDIC     ",
                    "sisnom": "SISTEMA JUDICIAL",
                    "sisest": "1",
                    "sisdes": "SISTEMA PARA CASOS LEGALES",
                    "estreg": "1",
                    "usureg": null,
                    "fecreg": "2013-02-07",
                    "usumod": null,
                    "fecmod": null
                },
                "padre": null,
                "mencod": 43,
                "estreg": "1",
                "menest": "1",
                "menrut": null,
                "usureg": null,
                "fecreg": "2013-02-08",
                "usumod": null,
                "fecmod": null,
                "mennom": "Consultas y Reportes",
                "menpadflg": "1",
                "menord": 2,
                "mensig": "JUDIC_MH_CONREP     ",
                "menico": null
            },
            "mencod": 407,
            "estreg": "1",
            "menest": "1",
            "menrut": "~/WebApp/Reportes/Reporte_Mensual.aspx",
            "usureg": null,
            "fecreg": "2016-07-13",
            "usumod": null,
            "fecmod": "2016-09-30",
            "mennom": "Balance de Nuevos Expedientes",
            "menpadflg": "0",
            "menord": 10,
            "mensig": "JUDIC_MH_BALEXP     ",
            "menico": null
        },
        "estreg": "1",
        "usureg": "1",
        "fecreg": "2019-08-16",
        "usumod": null,
        "fecmod": null
    }];
  }
